services:
  - type: web
    name: kashif-portfolio
    runtime: static
    rootDir: Kashif-Portfolio
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
